if v:version < 802
    packadd! dracula
endif
set termguicolors
highlight Normal ctermbg=NONE guibg=NONE
highlight NonText ctermbg=NONE guibg=NONE
highlight LineNr ctermbg=NONE guibg=NONE
highlight SignColumn ctermbg=NONE guibg=NONE
set cursorline
highlight CursorLine guibg=#f8f8f2
set laststatus=2
set noshowmode
set number
set norelativenumber
set mouse=a
set tabstop=4
set shiftwidth=4
set expandtab
set smartindent
set autoindent
set scrolloff=8
set incsearch
set ignorecase smartcase
set wildmenu
set splitbelow splitright
set undofile
set noswapfile
set lazyredraw
set updatetime=300
set timeoutlen=500
filetype plugin indent on
syntax enable
colorscheme dracula
call plug#begin('~/.vim/plugged')
Plug 'preservim/nerdtree'
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'airblade/vim-gitgutter'
Plug 'itchyny/lightline.vim'
Plug 'nvim-treesitter/nvim-treesitter', {'do': ':TSUpdate'}
call plug#end()
nnoremap <C-n> :NERDTreeToggle<CR>
nnoremap <C-p> :Files<CR>
